name: Generate github tag version â˜•

on:
  push:
    branches: [master]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '--skip-tagging')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installing Composer dependencies â¬‡ï¸
        run: composer install --prefer-dist --no-progress

      - name: Removing development folders ğŸ—‘ï¸
        run: |
          rm -r -f tests/

      - name: Removing development files ğŸ—‘ï¸
        run: |
          rm -f composer.lock
          rm -f CONTRIBUTING.md
          rm -f CODE_OF_CONDUCT.md
          rm -f phpunit.xml
          rm -f phpunit.xml.bak
          rm -f README.md
          rm -f .gitignore

      - name: Create a new GitHub tag ğŸ¤–
        run: |
          TAG_VERSION=$(bash .github/tags.sh)
          rm -r -f .github/

          git config --global user.email "aguiartgv@gmail.com"
          git config --global user.name "Matheus Aguiar"

          git add .
          git commit -am "build: Building correios-php new version"

          git tag -a v$TAG_VERSION -m "Add new tag version: v$TAG_VERSION"
          git push origin v$TAG_VERSION

          echo "All right! ğŸ‰"

      - name: Update the packagist version â¬†ï¸
        run: |
          curl \
            -X POST \
            -H "Content Type: application/json" \
            -H "Secret: ${{ secrets.PACKAGISTTOKEN }}" \
            https://packagist.org/api/github?username=devaguia
            
